M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Thu 22 Feb 2024 06:41:09 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-22T18:41:09-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X4.699Y45.466
X4.699Y4.826
X95.123Y45.466
X95.123Y4.826
M30
